on:
    push:
        branches:
            - main
    pull_request: ~

jobs:
    build:
        runs-on: 'ubuntu-latest'
        name: 'Build'
        steps:
            - name: 'Checkout'
              uses: 'actions/checkout@v4'
            - run: 'corepack enable'
            - run: 'sudo apt-get -y install graphicsmagick --no-install-recommends'
            - name: 'Install Node'
              uses: 'actions/setup-node@v4'
              with:
                  node-version-file: 'package.json'
                  cache: 'yarn'
            - run: 'yarn install --immutable'

            - name: Login to Container Registry
              uses: docker/login-action@v3
              with:
                  registry: registry.gkny.fr
                  username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
                  password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

            - name: 'Set up Docker Buildx'
              uses: 'docker/setup-buildx-action@v3'
            - name: 'Run Bake'
              run: 'yarn bake'
