on:
    push:
        branches:
            - main
    pull_request: ~

jobs:
    build:
        runs-on: 'ubuntu-latest'
        name: 'Build'
        steps:
            - name: 'Checkout'
              uses: 'actions/checkout@v4'
            - run: 'corepack enable'
            - name: 'Install Node'
              uses: 'actions/setup-node@v4'
              with:
                  node-version-file: 'package.json'
                  cache: 'yarn'
            - run: 'yarn install --immutable'

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: 'Set up Docker Buildx'
              uses: 'docker/setup-buildx-action@v3'
            - name: 'Run Bake'
              run: 'yarn bake'
